/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    posts: Post;
    files: File;
    journals: Journal;
    groupings: Grouping;
  };
  globals: {};
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean;
  apiKey?: string;
  apiKeyIndex?: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Post {
  id: string;
  title: string;
  content?: {
    [k: string]: unknown;
  }[];
  author?: string | User;
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface File {
  id: string;
  alt?: string;
  originalFilename?: string;
  metaData?: string;
  tags?: {
    tag?: string;
    id?: string;
  }[];
  prefix?: string;
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface Journal {
  id: string;
  entryAt: string;
  title?: string;
  richTextContent?: {
    [k: string]: unknown;
  }[];
  textContent?: string;
  summary?: string;
  attachments?: {
    file: string | File;
    description?: string;
    id?: string;
  }[];
  webResources?: (
    | {
        url: string;
        title?: string;
        description?: string;
        imageUrl?: string;
        siteName?: string;
        crawledAt?: string;
        id?: string;
        blockName?: string;
        blockType: 'general';
      }
    | {
        url: string;
        title?: string;
        description?: string;
        imageUrl?: string;
        siteName?: string;
        videoId?: string;
        channelTitle?: string;
        duration?: string;
        viewCount?: number;
        image?: string | File;
        crawledAt?: string;
        id?: string;
        blockName?: string;
        blockType: 'youtube';
      }
    | {
        url: string;
        title?: string;
        description?: string;
        imageUrl?: string;
        siteName?: string;
        placeId?: string;
        formattedAddress?: string;
        /**
         * @minItems 2
         * @maxItems 2
         */
        location?: [number, number];
        rating?: number;
        userRatingsTotal?: number;
        image?: string | File;
        crawledAt?: string;
        id?: string;
        blockName?: string;
        blockType: 'googleMap';
      }
  )[];
  comments?: {
    commentDate?: string;
    commentBody: string;
    id?: string;
  }[];
  isFavorite?: boolean;
  isPinned?: boolean;
  notebook?: string;
  tags?: {
    tag?: string;
    id?: string;
  }[];
  moodLabel?: string;
  moodScore?: number;
  activities?: {
    activity?: string;
    id?: string;
  }[];
  location?: {
    latitude?: number;
    longitude?: number;
    name?: string;
    address?: string;
    altitude?: number;
  };
  weather?: {
    temperature?: number;
    humidity?: number;
    pressure?: number;
    condition?: string;
  };
  timezone?: string;
  deviceName?: string;
  stepCount?: number;
  source?: {
    appName?: string;
    originalId?: string;
    importedAt?: string;
    rawData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  created_at?: string;
  modified_at?: string;
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Grouping {
  id: string;
  title: string;
  description?: string;
  type: 'static' | 'dynamic';
  rules?: {
    dateStart?: string;
    dateEnd?: string;
    tags?: {
      tag?: string;
      id?: string;
    }[];
    moods?: {
      mood?: string;
      id?: string;
    }[];
  };
  journals?: string[] | Journal[];
  journalCount?: number;
  updatedAt: string;
  createdAt: string;
}
