/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    posts: Post;
    files: File;
    journals: Journal;
  };
  globals: {};
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Post {
  id: string;
  title: string;
  content?: {
    [k: string]: unknown;
  }[];
  author?: string | User;
  updatedAt: string;
  createdAt: string;
}
export interface File {
  id: string;
  originalFilename?: string;
  alt?: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {};
}
export interface Journal {
  id: string;
  entryAt: string;
  title?: string;
  richTextContent?: {
    [k: string]: unknown;
  }[];
  textContent?: string;
  attachments?: {
    file: string | File;
    id?: string;
  }[];
  isFavorite?: boolean;
  isPinned?: boolean;
  notebook?: string;
  tags?: {
    tag?: string;
    id?: string;
  }[];
  moodLabel?: string;
  moodScore?: number;
  activities?: {
    activity?: string;
    id?: string;
  }[];
  location?: {
    latitude?: number;
    longitude?: number;
    name?: string;
    address?: string;
    altitude?: number;
  };
  weather?: {
    temperature?: number;
    humidity?: number;
    pressure?: number;
    condition?: string;
  };
  timezone?: string;
  deviceName?: string;
  stepCount?: number;
  source?: {
    appName?: string;
    originalId?: string;
    importedAt?: string;
    rawData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  created_at?: string;
  modified_at?: string;
  updatedAt: string;
  createdAt: string;
}
