/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    files: File;
    journals: Journal;
    groupings: Grouping;
  };
  globals: {};
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean;
  apiKey?: string;
  apiKeyIndex?: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface File {
  id: string;
  encryption: {
    scope: 'none' | 'partial' | 'full';
    algorithm?: string;
    keyId?: string;
    encryptedAt?: string;
  };
  alt?: string;
  altAuthorship: {
    authorType: 'human' | 'ai';
    aiMeta?: {
      provider?: 'anthropic' | 'openai' | 'google' | 'other';
      model?: string;
      respondedAt?: string;
    };
  };
  originalFilename?: string;
  metaData?: string;
  tags?: {
    tag?: string;
    authorType: 'human' | 'ai';
    aiMeta?: {
      provider?: 'anthropic' | 'openai' | 'google' | 'other';
      model?: string;
      respondedAt?: string;
    };
    id?: string;
  }[];
  properties?: {
    key: string;
    value: string;
    id?: string;
  }[];
  comments?: {
    commentDate?: string;
    commentBody: string;
    authorType: 'human' | 'ai';
    aiMeta?: {
      provider?: 'anthropic' | 'openai' | 'google' | 'other';
      model?: string;
      respondedAt?: string;
    };
    id?: string;
  }[];
  fileType?: 'image' | 'video' | 'audio' | 'other';
  imageDetails?: {
    width?: number;
    height?: number;
    exif?: string;
  };
  aiAnalysis?: {
    ocr?: {
      text?: string;
      provider?: 'anthropic' | 'openai' | 'google' | 'other';
      model?: string;
      analyzedAt?: string;
    };
    description?: {
      text?: string;
      tags?: {
        item?: string;
        id?: string;
      }[];
      provider?: 'anthropic' | 'openai' | 'google' | 'other';
      model?: string;
      analyzedAt?: string;
    };
  };
  prefix?: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface Journal {
  id: string;
  encryption: {
    scope: 'none' | 'partial' | 'full';
    algorithm?: string;
    keyId?: string;
    encryptedAt?: string;
  };
  entryAt: string;
  title?: string;
  titleAuthorship: {
    authorType: 'human' | 'ai';
    aiMeta?: {
      provider?: 'anthropic' | 'openai' | 'google' | 'other';
      model?: string;
      respondedAt?: string;
    };
  };
  richTextContent?: {
    [k: string]: unknown;
  }[];
  textContent?: string;
  summary?: string;
  summaryAuthorship: {
    authorType: 'human' | 'ai';
    aiMeta?: {
      provider?: 'anthropic' | 'openai' | 'google' | 'other';
      model?: string;
      respondedAt?: string;
    };
  };
  attachments?: {
    file: string | File;
    description?: string;
    id?: string;
  }[];
  webResources?: {
    url: string;
    title?: string;
    description?: string;
    imageUrl?: string;
    image?: string | File;
    siteName?: string;
    crawledAt?: string;
    tags?: {
      tag?: string;
      authorType: 'human' | 'ai';
      aiMeta?: {
        provider?: 'anthropic' | 'openai' | 'google' | 'other';
        model?: string;
        respondedAt?: string;
      };
      id?: string;
    }[];
    comments?: {
      commentDate?: string;
      commentBody: string;
      authorType: 'human' | 'ai';
      aiMeta?: {
        provider?: 'anthropic' | 'openai' | 'google' | 'other';
        model?: string;
        respondedAt?: string;
      };
      id?: string;
    }[];
    id?: string;
  }[];
  comments?: {
    commentDate?: string;
    commentBody: string;
    authorType: 'human' | 'ai';
    aiMeta?: {
      provider?: 'anthropic' | 'openai' | 'google' | 'other';
      model?: string;
      respondedAt?: string;
    };
    id?: string;
  }[];
  isFavorite?: boolean;
  isPinned?: boolean;
  notebook?: string;
  tags?: {
    tag?: string;
    authorType: 'human' | 'ai';
    aiMeta?: {
      provider?: 'anthropic' | 'openai' | 'google' | 'other';
      model?: string;
      respondedAt?: string;
    };
    id?: string;
  }[];
  properties?: {
    key: string;
    value: string;
    id?: string;
  }[];
  moodLabel?: string;
  moodScore?: number;
  activities?: {
    activity?: string;
    id?: string;
  }[];
  location?: {
    latitude?: number;
    longitude?: number;
    name?: string;
    address?: string;
    altitude?: number;
  };
  weather?: {
    temperature?: number;
    humidity?: number;
    pressure?: number;
    condition?: string;
  };
  timezone?: string;
  deviceName?: string;
  stepCount?: number;
  source?: {
    appName?: string;
    originalId?: string;
    importedAt?: string;
    rawData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  created_at?: string;
  modified_at?: string;
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Grouping {
  id: string;
  title: string;
  description?: string;
  type: 'static' | 'dynamic';
  rules?: {
    dateStart?: string;
    dateEnd?: string;
    tags?: {
      tag?: string;
      id?: string;
    }[];
    moods?: {
      mood?: string;
      id?: string;
    }[];
  };
  journals?: string[] | Journal[];
  journalCount?: number;
  updatedAt: string;
  createdAt: string;
}
